data_path: '/cosma/home/dp322/dc-guan2/fitting/pipeline/data/QSO/'

data_files:
    '0': 'pk0_CubicBox_rsd_phmean'
    '2': 'pk2_CubicBox_rsd_phmean'
    '000': 'bk000_diag_CubicBox_rsd_phmean'
    '202': 'bk202_diag_CubicBox_rsd_phmean'

cov_file: 'new_cov_QSO_0-2-4_000-202.npy'
number_of_mocks: 1000
rescale: false

path_to_save: '/cosma8/data/dp322/dc-guan2/results/QSO/'
file_name: 'p0p2b0b2_naut_noresc_fixedparams'

k_edges:
    '0':
        - 0.02
        - 0.20
    '2':
        - 0.02
        - 0.20
    '000':
        - 0.02
        - 0.10
    '202':
        - 0.02
        - 0.10

mean_density: 2.e-4
redshift: 1.4
cache_path: '/cosma/apps/dp322/dc-guan2/emulator/QSO/cosmo2/cache/z1.4/'

prior:
    'omega_cdm':
        'type': 'Uni'
        'lim':
            - 0.102
            - 0.139
    'omega_b':
        'type': 'Gauss'
        'lim':
            - 0.02218
            - 0.00055
    'h':
        'type': 'Uni'
        'lim':
            - 0.575
            - 0.747
    'n_s':
        'type': 'Fix'
        'lim': 0.9649
            
    'ln10^{10}A_s':
        'type': 'Uni'
        'lim':
            - 2.3
            - 3.8
    'b1':
        'type': 'Uni'
        'lim':
            - 0
            - 4
    'b2':
        'type': 'Uni'
        'lim':
            - -15
            - 15
    'bG2':
        'type': 'Uni'
        'lim':
            - -15
            - 15
    'bGamma3':
        'type': 'Fix'
        'lim': -2.40738
    'c0':
        'type': 'Fix'
        'lim': 20.35965
    'c2pp':
        'type': 'Fix'
        'lim': 69.88978
    'ch':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c1':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c2':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'Pshot':
        'type': 'Fix'
        'lim': -0.96323
    'a0':
        'type': 'Fix'
        'lim': 0.59054
    'Bshot':
        'type': 'Uni'
        'lim':
            - -10
            - 10
