data_path: '/Users/austerlitz/Desktop/TripoSH-Fitting-v2/data/QSO/'

data_files:
    '0': 'pk0_CubicBox_rsd_phmean'
    '2': 'pk2_CubicBox_rsd_phmean'
    '000': 'bk000_diag_CubicBox_rsd_phmean'
    '202': 'bk202_diag_CubicBox_rsd_phmean'

cov_file: 'new_cov_QSO_0-2-4_000-202.npy'
number_of_mocks: 1000
rescale: false

path_to_save: '/Users/austerlitz/Desktop/TripoSH-Fitting-v2/results/QSO/'
file_name: 'p0p2b0b2_PNG_test'

k_edges:
    '0':
        - 0.02
        - 0.20
    '2':
        - 0.02
        - 0.20
    '000':
        - 0.02
        - 0.10
    '202':
        - 0.02
        - 0.10

mean_density: 2.e-4
redshift: 1.4
cache_path: '/Users/austerlitz/Desktop/TripoSH-Fitting-v2/cache/QSO/z1.4/'

prior:
    'omega_cdm':
        'type': 'Fix'
        'lim': 0.12
    'omega_b':
        'type': 'Fix'
        'lim': 0.02237
    'h':
        'type': 'Fix'
        'lim': 0.6736
    'n_s':
        'type': 'Fix'
        'lim': 0.9649
            
    'ln10^{10}A_s':
        'type': 'Fix'
        'lim': 3.03639
    'b1':
        'type': 'Uni'
        'lim':
            - 0
            - 4
    'b2':
        'type': 'Uni'
        'lim':
            - -15
            - 15
    'bG2':
        'type': 'Uni'
        'lim':
            - -15
            - 15
    'bGamma3':
        'type': 'Fix'
        'lim': -2.40738
    'c0':
        'type': 'Fix'
        'lim': 20.35965
    'c2pp':
        'type': 'Fix'
        'lim': 69.88978
    'ch':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c1':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'c2':
        'type': 'Uni'
        'lim':
            - -1000
            - 1000
    'Pshot':
        'type': 'Fix'
        'lim': -0.96323
    'a0':
        'type': 'Fix'
        'lim': 0.59054
    'Bshot':
        'type': 'Uni'
        'lim':
            - -10
            - 10
    'fnlequi':
        'type': 'Uni'
        'lim':
            - -5000
            - 5000
    fnlortho':
        'type': 'Uni'
        'lim':
            - -5000
            - 5000
